spring:
  application:
    name: deutschbridge-backend

  #Email configuration
  mail:
    host: localhost
    port: 1025
    username: aliemran2022@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  lifecycle:
    timeout-per-shutdown-phase: 20s


    #Postgresql setting
  datasource:
    url: ${POSTGRES_URI}


  ai:
    ollama:
      chat:
        options:
          model: gemma3:1b


  #MongoDB settings
  data:
    mongodb:
      uri: ${MONGODB_URI}


  #JPA and Hibernate settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

ollama:
  api:
    key: ${OLLAMA_API_KEY}
    url: ${OLLAMA_API_URI}

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG


server:
  shutdown: graceful

jwt.secret: ${JWT_SECRET}
